name: login
description: Show content depending on whether or not the user is logged in. Simply provide two arguments - a Widget to display when logged in, one to display when not. Based on the firebase_auth and google_sign_in packages.
version: 1.0.0
authors:
  - Christian Lewis <ctjl96@gmail.com>
  - The Hercules Team <hello@hercules.dev>
homepage: https://github.com/ctjl96/login

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # auth stuff
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/